INSERT DATA
{
  GRAPH <http://mu.semte.ch/graphs/harvesting> 
  {
 	<http://redpencil.data.gift/id/scheduled-job/g4ggb738max-e462-46b4-abf5-103d1a1854d0> a <http://vocab.deri.ie/cogs#ScheduledJob>;
	<http://purl.org/dc/terms/created> "2024-01-26T15:06:01.294Z";
	<http://purl.org/dc/terms/modified> "2024-01-26T15:06:01.294Z";
	<http://redpencil.data.gift/vocabularies/tasks/operation> <http://redpencil.data.gift/id/jobs/concept/JobOperation/cleanup>;
	<http://redpencil.data.gift/vocabularies/tasks/schedule> <http://redpencil.data.gift/id/cron-schedule/tabaj980-935e-4df8-9de8-724321ad881a>;
	<http://mu.semte.ch/vocabularies/core/uuid> "g4ggb738max-e462-46b4-abf5-103d1a1854d0";
	<http://purl.org/dc/terms/creator> <http://lblod.data.gift/services/job-self-service>;
	<http://purl.org/dc/terms/title> "Cleanup".


	<http://redpencil.data.gift/id/cron-schedule/tabaj980-935e-4df8-9de8-724321ad881a> a <http://redpencil.data.gift/vocabularies/tasks/CronSchedule>;
	<http://schema.org/repeatFrequency>  "38 4,5,16,14,15 * * *";
		<http://mu.semte.ch/vocabularies/core/uuid> "tabaj980-935e-4df8-9de8-724321ad881a".
	
	
	
<http://redpencil.data.gift/id/scheduled-task/v2ej8999-e97d-452a-a22c-vee4575715be> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://redpencil.data.gift/vocabularies/tasks/ScheduledTask> .
<http://redpencil.data.gift/id/scheduled-task/v2ej8999-e97d-452a-a22c-vee4575715be> <http://mu.semte.ch/vocabularies/core/uuid> "v2ej8900-e97d-452a-a22c-vee4575715be" .
<http://redpencil.data.gift/id/scheduled-task/v2ej8999-e97d-452a-a22c-vee4575715be> <http://purl.org/dc/terms/created> "2024-01-26T15:06:01.265Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
<http://redpencil.data.gift/id/scheduled-task/v2ej8999-e97d-452a-a22c-vee4575715be> <http://purl.org/dc/terms/modified> "2024-01-26T15:06:01.265Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
<http://redpencil.data.gift/id/scheduled-task/v2ej8999-e97d-452a-a22c-vee4575715be> <http://redpencil.data.gift/vocabularies/tasks/operation> <http://lblod.data.gift/id/jobs/concept/TaskOperation/cleaning> .
<http://redpencil.data.gift/id/scheduled-task/v2ej8999-e97d-452a-a22c-vee4575715be> <http://redpencil.data.gift/vocabularies/tasks/index> "0"^^<http://www.w3.org/2001/XMLSchema#integer>.
<http://redpencil.data.gift/id/scheduled-task/v2ej8999-e97d-452a-a22c-vee4575715be> <http://purl.org/dc/terms/isPartOf> <http://redpencil.data.gift/id/scheduled-job/g4ggb738max-e462-46b4-abf5-103d1a1854d0> .

  }
}


